module.exports = {
    check: require('./check'),
    delete: require('./delete'),
    login: require('./login'),
    logout: require('./logout'),
    mypage: require('./mypage'),
    pwcheck: require('./pwcheck'),
    find: require('./find'),
    pwupdate: require('./pwupdate'),
    search: require('./search'),
    send: require('./send'),
    signup: require('./signup'),
    tokens: require('./tokens'),
    update: require('./update'),
    chat: require('./chat'),
}